name: Data_Pipeline_CI/CD with Artifact

on:
  push:
    branches:
      - main

jobs:
  build_test:
    name: Build and Test Data Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover tests/
    
    - name: Generate test report
      run: |
        echo "Test Report" > test_report.txt
        echo "All tests passed successfully" >> test_report.txt
    
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test_report.txt

  staging:
    name: Staging Environment
    runs-on: ubuntu-latest
    needs: build_test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download test report
      uses: actions/download-artifact@v4
      with:
        name: test-report
    
    - name: Display test report
      run: cat test_report.txt
    
    - name: Test Staging Environment
      run: |
        echo "Running staging tests..."
    
    - name: Generate staging report
      run: |
        echo "Staging Report" > staging_report.txt
        echo "All staging tests passed successfully" >> staging_report.txt
    
    - name: Upload staging report
      uses: actions/upload-artifact@v4
      with:
        name: staging-report
        path: staging_report.txt

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download staging report
      uses: actions/download-artifact@v4
      with:
        name: staging-report
    
    - name: Display staging report
      run: cat staging_report.txt
    
    - name: Deploy Data Pipeline
      run: |
        python data_pipeline.py

    - name: Generate deployment report
      run: |
        echo "Deployment Report" > deployment_report.txt
        echo "Data pipeline deployed successfully" >> deployment_report.txt
    
    - name: Upload deployment report
      uses: actions/upload-artifact@v4
      with:
        name: deployment-report
        path: deployment_report.txt