name: Node CI

on:
  push:
    branches:
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Write content file
        run: echo "hello world from artifact" > hello_world.txt
      - name: Upload file to artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./hello_world.txt
